global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "product-inventory"
    metrics_path: /metrics
    static_configs:
      - targets: ["product-inventory:3002"]

  - job_name: "product-catalog"
    static_configs:
      - targets: ["product-catalog:3001"]

  - job_name: "profile-management"
    static_configs:
      - targets: ["profile-management:3003"]

  - job_name: "contact-support-team"
    static_configs:
      - targets: ["contact-support-team:8000"]